export { default as createArqMorto } from './createArqMorto'
export { default as createBook } from './createBook'
export { default as createNotStudent } from './createNotStudent'
export { default as createPeople } from './createPeople'
export { default as createStudent } from './createStudent'
